# Generated by Django 4.2.23 on 2025-09-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reglas',
            fields=[
                ('id_reglas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_reglas', models.CharField(max_length=100)),
                ('descripcion_reglas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Reglas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('genero_usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula_usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('email_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('password_usuario', models.CharField(max_length=200)),
                ('fecha_registro_usuario', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Usuario_Rol',
                'managed': False,
            },
        ),
    ]
