# Generated by Django 4.2.23 on 2025-10-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medessentia', '0008_horariodoctor_id_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='horariodoctor',
            name='uq_horario_doctor_dia_tramo',
        ),
        migrations.AddField(
            model_name='horariodoctor',
            name='es_recurrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horariodoctor',
            name='fecha_fin',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariodoctor',
            name='fecha_inicio',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariodoctor',
            name='tipo_horario',
            field=models.CharField(choices=[('TRABAJO', 'Horario de Trabajo'), ('ALMUERZO', 'Horario de Almuerzo'), ('DESCANSO', 'Descanso')], default='TRABAJO', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='horariodoctor',
            constraint=models.UniqueConstraint(fields=('id_doctor', 'fecha_inicio', 'fecha_fin', 'dia_semana', 'hora_inicio', 'hora_fin'), name='uq_horario_doctor_periodo'),
        ),
    ]
