# Generated by Django 4.2.23 on 2025-10-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medessentia', '0009_remove_horariodoctor_uq_horario_doctor_dia_tramo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='id_doctor',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='id_paciente',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='horariodoctor',
            name='id_doctor',
        ),
        migrations.DeleteModel(
            name='ArchivoAtencion',
        ),
        migrations.DeleteModel(
            name='ArchivoCita',
        ),
        migrations.DeleteModel(
            name='Atencion',
        ),
        migrations.DeleteModel(
            name='AtencionCie10',
        ),
        migrations.DeleteModel(
            name='EncuestaCita',
        ),
        migrations.DeleteModel(
            name='ExamenFisico',
        ),
        migrations.DeleteModel(
            name='HistoriaCie10',
        ),
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='RevisionSistemas',
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='HorarioDoctor',
        ),
    ]
