# Generated by Django 4.2.23 on 2025-10-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medessentia', '0010_remove_cita_id_doctor_remove_cita_id_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_elaboracion', models.DateField()),
                ('expediente_no', models.CharField(max_length=50, unique=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('VIUDO', 'Viudo'), ('UNION_LIBRE', 'Unión libre'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=120, null=True)),
                ('grupo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=15)),
                ('alimentacion', models.TextField(blank=True, null=True)),
                ('higiene', models.TextField(blank=True, null=True)),
                ('inmunizaciones', models.TextField(blank=True, null=True)),
                ('quirurgicos', models.TextField(blank=True, null=True)),
                ('traumaticos', models.TextField(blank=True, null=True)),
                ('transfusionales', models.TextField(blank=True, null=True)),
                ('alergicos', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historia_clinica',
                'managed': False,
            },
        ),
    ]
